### ISSUE TITLE
Wrong highlight area in Chinese

### ISSUE THREAD

**Issue by jyhsu2000** [JBlond/php-diff#1]
In the following screenshot,
the red area are different content, but the blue area (highlighted by this project) are the same content.
I think maybe there are some wrongs when handle unicode characters or full-width characters.
![screenshot_20170501_200112](https://cloud.githubusercontent.com/assets/6276648/25579290/1f47bd34-2ea9-11e7-8829-50503e7503df.png)

**Comment by JBlond** [comment]
Can post the shortest possible line of charakters that causes this effect. I will then look into it

**Comment by JBlond** [comment]
with https://github.com/JBlond/php-diff/commit/4c1bb3764e2ee4014bef0b5e754609853a66905b I tried to fix that. The example a.txt b.txt is working now. Please check yours.

**Comment by jyhsu2000** [comment]
Sorry for forgetting post the text for test.
The following are the lines in the screenshot.
```
另外我覺得那個評價的白色櫃子有點沒有必要欸。外觀我就不說了 ，怎麼連空間都那麼狹隘。不過倒是從這個地方看出所謂的“改革” 😅😅
```
```
另外我覺得那個評鑑的白色櫃子有點沒有必要欸。外觀我就不說了 ，怎麼連空間都那麼狹隘。不過倒是從這個地方看出所謂的“改革” 😅😅
```
I tried to update to latest version (d3eb3ab45c46b07db680815d6fa4f0b28f89e886)
and it works fine now.
Thanks.
![screenshot_20170506_005139](https://cloud.githubusercontent.com/assets/6276648/25755681/83e3170c-31f6-11e7-8102-fcc6d4b2e87f.png)
