### ISSUE TITLE
Add collapsed lines to opCodes

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#109]
This is just a suggestion and I would like to know your opinion about it.

There's an option called `context` which defines how many lines around a changed one remain visible.
Equal lines around those context are 'collapsed' and removed from the output.

How about we introduce a new tag which contains the collapsed lines so decision and way of including those lines can be done at renderer level?
E.g.
* Do or Don't include them.
* Don't include them, but mark them as collapsed with a symbol (like we do now with ...)
* Do include them, but toggle the visibility using js/css.

Warning: At this point I'm not entirely sure what impact this change will have on how the renderers and statistics are currently implemented.

**Comment by JBlond** [comment]
I assume you talk about this [context](https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/SequenceMatcher.php#L75) in the SequenceMatcher.

I like the idea. It is like the command line diff options

```man
       -c, -C NUM, --context[=NUM]
              output NUM (default 3) lines of copied context

       -u, -U NUM, --unified[=NUM]
              output NUM (default 3) lines of unified context
```

If I remember correctly this has to be done in function [getGroupedOpCodes](https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/SequenceMatcher.php#L231) and would also affect [function renderSequences](https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/Renderer/MainRenderer.php#L124)

**Comment by DigiLive** [comment]
The "context" option defines the amount of visible lines around blocks with differences.
Unchanged lines between those "context" lines are not included in the grouped opcodes and therefor treated as "collapsed".
Currently this results in `...`

I'd like to include the unchanged lines between those context so we have more saying about what to do with them.

**Comment by JBlond** [comment]
As I said, I like the idea. You can start with it.

**Comment by DigiLive** [comment]
@JBlond Branch [php-diff-109](https://github.com/JBlond/php-diff/tree/php-diff-109) is pushed for preliminary preview.

**Comment by DigiLive** [comment]
Every 2nd line or every second group of the grouped opCodes?

**Comment by JBlond** [comment]
Yepp
Text\Unified line 38 for example

**Comment by DigiLive** [comment]
> I wonder what it is about the `$key % 2`. If I read that correctly it should skip every second line.

It skips every second group of opCodes.
Which are the lines that where previously stripped out because they're considered to be out of context.

**Comment by DigiLive** [comment]
Did you had any chance to check the code so far?

**Comment by JBlond** [comment]
@DigiLive Yepp, it looks fine. You only need to fix HtmlRenderersTest.php
I thought you would open a PR when you are ready.

**Comment by DigiLive** [comment]
> @DigiLive I thought you would open a PR when you are ready.

I will... wanted to make sure things weren't baloney before creating a PR.
