### ISSUE TITLE
PHP notice in SequenceMatcher.php

### ISSUE THREAD

**Issue by brainfork** [JBlond/php-diff#112]
My company was utilizing [chrisboulton/php-diff](https://github.com/chrisboulton/php-diff/) in our code and have had to replace it as part of an ongoing upgrade to PHP 8.  We've replaced that repo with this one and ran PHPStan scans on it which returned this notice:

``` ------ -------------------------------------------------------------
  Line   \lib\Diff\SequenceMatcher.php
 ------ -------------------------------------------------------------
  372    Call to function unset() contains undefined variable $line.
 ------ -------------------------------------------------------------
```

I believe a fix for this would be to simply define `$line = ''` above the if statement here: 
https://github.com/JBlond/php-diff/blob/2dc83441c2a66156c8b9dc9a508d32fed27d7765/lib/jblond/Diff/SequenceMatcher.php#L359

**Comment by DigiLive** [comment]
Hello @brainfork,

Thank you for your feedback.
I think https://github.com/JBlond/php-diff/blob/2dc83441c2a66156c8b9dc9a508d32fed27d7765/lib/jblond/Diff/SequenceMatcher.php#L372 can be removed all together.
Looks like the reference isn't kept after using `array_walk()`: https://3v4l.org/jAE8s

**Comment by DigiLive** [comment]
@JBlond You're picking this one up?

**Comment by JBlond** [comment]
Yes, I will. I'm busy, but as soon as possible I'm looking into this.

**Comment by JBlond** [comment]
@DigiLive Do we need to make a release?

**Comment by DigiLive** [comment]
The package will run just fine as currently released.
It's the user's analyzer which warns him about the necessary line.

IMHO, we don't **need** a release, but it will not harm anything.
You expect more changes anytime soon?
