### ISSUE TITLE
Calling generateSkippedTable

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#17]
This is not really an issue, but I'm trying to understand the code so I can apply changes properly to contribute and to adapt it to my needs.

When is the following method of the renderer called as defined in file `Inline.php` ?

```php
    /**
     * Generates a string representation of empty table body.
     *
     * @return string Html code representing empty table body.
     */
    public function generateSkippedTable(): string
    {
        $html = '<tbody class="Skipped">';
        $html .= '<th>&hellip;</th>';
        $html .= '<th>&hellip;</th>';
        $html .= '<td>&#xA0;</td>';
        $html .= '</tbody>';
        return $html;
    }
```

It's called here in file `HtmlArray.php`:
```php
            // If this is a separate block, we're condensing code so output ...,
            // indicating a significant portion of the code has been collapsed as
            // it is the same
            if ($i > 0) {
                $html .= $object->generateSkippedTable();
            }
```
but whatever I try, `$i` is always 0.

**Comment by JBlond** [comment]
I adopted the code. It might be that you found a bug. I will investigate that. Thank you for opening this issue.

**Comment by JBlond** [comment]
Thanks a lot for finding this dead code

**Comment by JBlond** [comment]
@DigiLive What kind of Change you would like to have fopr your needs? Feel free to open a PR from development branch.

**Comment by DigiLive** [comment]
@JBlond I'm still exploring the code, but I'll certainly open an PR when I've implemented changes which might be useful for you as well.
The first thing that came to mind is to explode the strings/lines inside the class instead of requiring array parameters for the contstructor.
(Allowing array as well as string or throw InvalidArgumentException for any other).

Back to topic...
I'm not sure the mentioned code must be considered as death code. It seems logical to replace a large block of unchanged lines by a ellipse. I'd rather see this code being used when enabled as an option.

**Comment by DigiLive** [comment]
Method `$object::generateSkippedTable();` does get called in `HtmlArray.php`.
Condition `$i > 0` (@ `HtmlArray::renderHtml()`) can be `true`, depending on the `context` option and the texts which are compared to each other.

It's `true` when a block of text in the 1st version is equal to a block of text in the 2nd version AND `block size > ($context * 2)`.

The value of `$context` defines how many equal lines before and after a difference between the compared versions will be showed. The block of equal lines in between is collapsed.
Collapsing was removed with commit 49e2c3a (suspected to be death code) and re-introduced with commit d445336.

**Note**: A block that would normally collapse, but its position is at the start or end of the text, will not be shown as collapsed. Those lines are **NOT** rendered at all.
@JBlond Maybe we can open another issue for this!?

To only show the differences between the two versions, set the value to `0`.
@JBlond Should this be the deafult value instead of 3?

To show all equal lines, set the value to be larger than the line count of the largest equal block of text of the 1st version. Practically, this will be the line count of the complete text of the 1st version.

In order to make this work correctly, `$context` can't have a negative value.
I will add a validation for this value in a future commit.

**Comment by JBlond** [comment]
@DigiLive Yes, sure open a new issue :) I have to look into this.

**Comment by JBlond** [comment]
@DigiLive with the example files, adding a `var_dump($i); ` after line [61](https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/Renderer/Html/HtmlArray.php#L61) always shows a 0.

**Comment by DigiLive** [comment]
> 
> 
> @DigiLive with the example files, adding a `var_dump($i); ` after line [61](https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/Renderer/Html/HtmlArray.php#L61) always shows a 0.

That's because the default value of the context-option is set to 3 and there's no more than (2x context-option) equal lines between the differences. To see this in action, set the context-option to a lower value, like 2 or duplicate line 15 `a.txt` and `b.txt` a couple of times.

**Comment by JBlond** [comment]
Maybe it helps to add a second example. c.txt and d.txt

**Comment by DigiLive** [comment]
My idea as well, but I wanted to wait untill bug #24 is closed.

**Comment by JBlond** [comment]
That idea was to test #24

**Comment by JBlond** [comment]
Done in https://github.com/JBlond/php-diff/pull/26
