### ISSUE TITLE
Code Commenting

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#19]
@JBlond 
I've forked the repo and did some cleanup/optimization and much code commenting.
Still trying to understand the scripts completely, I've refactored a lot of variables and made a lot of code commenting. Lot's of things are still unclear though.

If you're interested, I can add you as a contributor of my fork so we can both make effort to refactor/comment/optimize the code. This way we don't have to litter your repo, trying to understand the code.

**Comment by JBlond** [comment]
@DigiLive I could add you to my repo ;)

**Comment by DigiLive** [comment]
That's also fine for me. 😉
My intention was just to prevent littering your repo with many commits. That's why I didn't do a PR yet.

But I'm happy to contribute to yours directly.

**Comment by JBlond** [comment]
@DigiLive I added you to the repo. Feel free to contribute.
