### ISSUE TITLE
Collapsed block not shown at start of end of text.

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#24]
As mentioned [here](https://github.com/JBlond/php-diff/issues/17#issuecomment-579130958)...
A block that would normally collapse, but its position is at the start or end of the text, will not be shown as collapsed. Those lines are NOT rendered at all.

An indication for the block being collapsed from the start/to the end of the text should be visible or these blocks shouldn't be collapsed at all.
E.g.

| LineNo | LineContent |
| ------------- | ------------- |
| bof | |
| ... | ... |
| 10 | Hello World! |
| ... | ... |
| eof | |

**Comment by DigiLive** [comment]
The sequenceMatchter is responsible for removing the blocks at the start and end of the text.

Line 554 > 562 removes the sequences at the start.
```php
if ($opCodes['0']['0'] == 'equal') {
    $opCodes['0'] = array(
        $opCodes['0']['0'],
        max($opCodes['0']['1'], $opCodes['0']['2'] - $context),
        $opCodes['0']['2'],
        max($opCodes['0']['3'], $opCodes['0']['4'] - $context),
         $opCodes['0']['4']
    );
}

```
Line 564 > 574 removes the sequences at the end...
```php
$lastItem = count($opCodes) - 1;
if ($opCodes[$lastItem]['0'] == 'equal') {
    list($tag, $i1, $i2, $j1, $j2) = $opCodes[$lastItem];
    $opCodes[$lastItem] = array(
        $tag,
        $i1,
        min($i2, $i1 + $context),
        $j1,
        min($j2, $j1 + $context)
    );
}
```
in combination with line 604 > 606.
```php
if (!empty($group) && !(count($group) == 1 && $group[0][0] == 'equal')) {
    $groups[] = $group;
}
```

In order to show collapsed blocks at the start and end, the first 2 blocks of code should not be executed and the code at line 605 should.
Preferably (by me) create new option like `trimEqual` which strips equal blocks of text from the beginning and end.
![TrimEqualFalse](https://user-images.githubusercontent.com/7613487/73535344-9e622e00-4423-11ea-9b62-bf2fb0e1b671.png)
![TrimEqualTrue](https://user-images.githubusercontent.com/7613487/73535345-9e622e00-4423-11ea-8224-3cc8ce83dbe6.png)

**Comment by JBlond** [comment]
The original [diff ](https://gist.github.com/JBlond/fcea64ecc352bb8ba977541d88429bc8)on a command line diff -u a.txt b.txt  looks almost the same like now the sequence matcher. So I like your idea of having trimEqual as an option.

**Comment by DigiLive** [comment]
Ok.
I will implement it as an option.

I've researched a lot of code, but many code still remains Hocus pocus. 😅
Therefor I suggest testing it well before making a new release.

I'll also re-add the long Chinese line to the same commit.

**Comment by DigiLive** [comment]
Commit 98d993e also has some test added for `sequenceMatcher::getGroupedOpcodes()` to test the output with different options set.

**Comment by DigiLive** [comment]
@JBlond  Any chance to test the collapsing feature yet?

**Comment by JBlond** [comment]
Yepp, for me it works great.

**Comment by JBlond** [comment]
@DigiLive If you are fine with all your changes open another pull request.
