### ISSUE TITLE
Parameter number mismatch

### ISSUE THREAD

**Issue by JBlond** [JBlond/php-diff#27]
@DigiLive 
https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff.php#L240 uses a parameter, while the function has none https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff/SequenceMatcher.php#L546

**Comment by DigiLive** [comment]
Yes... I've found this myself also.
It's already fixed in my local repo.

Meanwhile the code isn't broken.
The context option is passed to the constructor of the sequenceMatcher at line 239.
