### ISSUE TITLE
SquenceMatcher $fullBCount not used

### ISSUE THREAD

**Issue by JBlond** [JBlond/php-diff#29]
$fullBCount in SquenceMatcher is not used anywhere else. Maybe it can be removed.

**Comment by DigiLive** [comment]
Did notice this one myself also. It was primarily used by methods for calculating similarity between two text sequences, of which I guess you've removed them.

Currently I'm refactoring the SequenceMatcher.
I can remove the property, or maybe I can reintroduce the similarity calculations.
