### ISSUE TITLE
PHP methods should not contain too much logic 

### ISSUE THREAD

**Issue by JBlond** [JBlond/php-diff#3]
100 lines for Diff_Renderer_Html_SideBySide::render() in lib/Diff/Renderer/Html/SideBySide.php, line 56
    80 lines for Diff_Renderer_Html_Inline::render() in lib/Diff/Renderer/Html/Inline.php, line 56
    54 lines for Diff_Renderer_Text_Context::render() in lib/Diff/Renderer/Text/Context.php, line 65
    53 lines for Diff_Renderer_Html_Array::render() in lib/Diff/Renderer/Html/Array.php, line 115

**Comment by Creris** [comment]
Hey,

I would like to do try to tackle this tomorrow morning.

**Comment by JBlond** [comment]
Thanks a lot for your PR https://github.com/JBlond/php-diff/pull/4
