### ISSUE TITLE
Side by side diff shows only partially all deleted lines

### ISSUE THREAD

**Issue by vendeeglobe** [JBlond/php-diff#32]
This happens only occasionally within the  side by side diff mode.

![Side_by_side-diff](https://user-images.githubusercontent.com/54716082/83946732-f31f1680-a812-11ea-83d1-5b82d9d1ab93.png)
![Inline-diff](https://user-images.githubusercontent.com/54716082/83946741-fadebb00-a812-11ea-82b5-91a1961288f5.png)

php-diff: v1.16
WackoWiki 6.0.7

**Comment by JBlond** [comment]
That is a css problem. @vendeeglobe Please inspect which WackoWiki css rule overrides the css rule from php-diff.

**Comment by vendeeglobe** [comment]
But then the missing lines should show up in the HTML and they are not.
https://wackowiki.org/doc/Dev/Release/R6.0/ReleaseNotes/diff?a=4076&b=0&diffmode=3

I can provide other examples.

**Comment by DigiLive** [comment]
Can you provide sample texts, so we can use them at our systems?

**Comment by vendeeglobe** [comment]
The text files with the source text for each revision.

Example 1:
https://wackowiki.org/doc/Dev/Release/R6.0/ReleaseNotes/diff?a=4076&b=0&diffmode=3
[example-1_r136.txt](https://github.com/JBlond/php-diff/files/4740633/example-1_r136.txt)
[example-1_r138.txt](https://github.com/JBlond/php-diff/files/4740634/example-1_r138.txt)

Example 2:
https://wackowiki.org/doc/News/2019/08/Unicode/diff?a=3175&b=0&diffmode=3
[example-2_r45.txt](https://github.com/JBlond/php-diff/files/4740635/example-2_r45.txt)
[example-2_r50.txt](https://github.com/JBlond/php-diff/files/4740636/example-2_r50.txt)

Examples can be use freely.
Here you can see that the same source is passed for both modes:
https://github.com/WackoWiki/wackowiki/blob/master/wacko/handler/page/diff.php#L336

**Comment by DigiLive** [comment]
Since commit c017af50, the string for the table rows of deleted lines are defined with the heredoc syntax at method `SideBySide::generateTableRowsDelete()`.

The concatenation is accidentally dropped with this change, which results in only returning the last row instead of all deleted rows.

I'll fix this bug, update the tests, examples and readme file and make PR.

**Comment by DigiLive** [comment]
I've made a PR which is waiting on JBlond to be reviewed and merged.

**Comment by JBlond** [comment]
@vendeeglobe There is now a release for it.

**Comment by JBlond** [comment]
@DigiLive I checked out 3e243f1 the last commit before the merge fix. I wonder why the phpunit test didn't fail.

**Comment by vendeeglobe** [comment]
Thanks for patching.

**Comment by DigiLive** [comment]
> 
> 
> @DigiLive I checked out [3e243f1](https://github.com/JBlond/php-diff/commit/3e243f1c9689cff26f03d7370dcc4ab7ea480cc4) the last commit before the merge fix. I wonder why the phpunit test didn't fail.

Theoretically...
- In that commit, the sample texts and the resulting texts are generated by us. The test is comparing them to match to each other. So we must make sure all have the correct content.
- In the sample texts of that commit there's only a block with 1 deleted line.
Having only 1 deleted line, there's no need to concatenate.

```php
$html1 = 'OneDeletedLine'
$html2 .= 'OneDeletedLine'
// $html2 == $html1
```
Therefor, I've updated the sample text to a block of 2 deleted lines.
```php
$html1 = 'fisrtDeletedLine';
$html1 = 'SecondDeletedLine';
$html2 .= 'fisrtDeletedLine';
$html2 .= 'secondDeletedLine';
// $html2 != $html1
// 'fisrtDeletedLineSecondDeletedLine' != 'SecondDeletedLine'

You might want to add more lines for the other type of changes as well (equal, inserted, replaced lines). Another (and maybe easier) method is to mock some of the classes.
```
