### ISSUE TITLE
First or last x lines of text are shown even when there's no difference between the two compared texts.

### ISSUE THREAD

**Issue by csalgadow** [JBlond/php-diff#50]
Hi
Thank you very much for this code that is very useful to me.
I would like to know if there is any method to know if there are no differences and thus not show anything or if it is possible to add it

**Comment by DigiLive** [comment]
As far as I'm aware most, if not all, renderers should produce either nothing or a string saying 'No differences found'.

To which renderer are you referring?

**Comment by JBlond** [comment]
@DigiLive There shouldn't be any output. However, when I compare a.txt with a.txt in the example folder I get a difference.

```diff
@@ -32,3 +32,3 @@
     </body>
 </html>
```

I tired the orginal from chrisboulton/php-diff. There it isn't. I will track that tomorrow which commit caused that.

**Comment by JBlond** [comment]
v1.15 doesn't have that issue. It came with v1.16

**Comment by JBlond** [comment]
98d993ef14bc7a254c0b060a33b77b3a0bd3c54d is the cause.

**Comment by DigiLive** [comment]
Agree... It's a combo of option `trimEqual` and `context`.
I think I've found where it goes wrong, but I need to verify some things because of the SequenceMatchers's complexity.

**Comment by DigiLive** [comment]
Related to issue #24.

**Comment by JBlond** [comment]
@csalgadow We need your feedback for the renderer

**Comment by csalgadow** [comment]
Thank you very much
I have downloaded the updated version and now it works very well, it gives message of differences not found except in Text Unified Diff Text Context Diff that does not output any text, although for me it is not necessary.

I will include your scipt in the online voting platform that I have at https://bitbucket.org/csalgadow/demokratian_votaciones/
The idea is that users can check if any of the scripts that collect the vote has been altered so that they can be sure that the vote is secure.

Again, thank you very much for your quick response and for your work with php-diff

**Comment by DigiLive** [comment]
You're very welcome.
If you have any other issues/suggestions, please let us know!
