### ISSUE TITLE
Add option to disable the table header

### ISSUE THREAD

**Issue by vendeeglobe** [JBlond/php-diff#53]
Currently we patch php-diff class for Inline and SideBySide diff mode, because the application add its own header with additional metadata. It would be nice to disable the header for instance via via the $customOptions.

```
    <thead>
        <tr>
            <th colspan="2">{$this->options['title1']}</th>
            <th colspan="2">{$this->options['title2']}</th>
        </tr>
    </thead>
```
![diff_without_header](https://user-images.githubusercontent.com/54716082/88179989-f9cfe480-cc2c-11ea-9373-72cbd8f80f3f.png)

**Comment by DigiLive** [comment]
This flexibility exists in the possibility to write your own renderer or to extend the included renderers by your own class which can override any of the original methods.
E.g.:
```php
<?php

declare(strict_types=1);

use jblond\Diff\Renderer\Html\SideBySide;

class WackoWikiSideBySide extends SideBySide
{
    /**
     * Generates a string representation of the opening of a predefined table and its header with titles from options.
     *
     * @return string HTML code representation of a table's header.
     */
    public function generateDiffHeader(): string
    {
        return <<<HTML
<table class="Differences DifferencesSideBySide">
    <thead>
        <tr>
            <th colspan="4">This is my overridden header</th>
        </tr>
    </thead>
HTML;
    }

}

```
```php
    //$renderer = new SideBySide();
    $renderer = new WackoWikiSideBySide();
    echo $diff->Render($renderer);
```

Currently the master branch includes an interface which can be implemented for writing your own renderer classes.

**Comment by JBlond** [comment]
I think we need to add those things to the documentation.

**Comment by DigiLive** [comment]
Yes... that's why I suggested to enable the Wiki for this repo.
Since the library is quite evolving now, there's need for a proper manual.
Makes it both easier for the user as for us.

**Comment by JBlond** [comment]
I enabled the wiki.

**Comment by JBlond** [comment]
After #54 is merged, we can publish a new version, so you @vendeeglobe have the option to use a customs override function and don't to patch this any longer.

**Comment by JBlond** [comment]
@vendeeglobe You can use v2.2.0
If you have another request let us know.

**Comment by DigiLive** [comment]
> 
> 
> I enabled the wiki.

I've cloned the wiki to my local machine... During next week, I will add content to it.

**Comment by vendeeglobe** [comment]
This solutions would suffice at least for **just** turning off the header in HTML renderer, without excluding the possibility of having your own header.

https://github.com/jfcherng/php-diff/commit/5f0dd2d5b3be6bcec5cd93dacacc37a7c7974003

**Comment by JBlond** [comment]
I look at that.

**Comment by DigiLive** [comment]
Did you look at the wiki and discussions?
https://github.com/JBlond/php-diff/discussions/96

All generated output can by modified as wished.

**Comment by JBlond** [comment]
Well I did. The one thing is an configuration option. The other one needs a bit more programming skills.

**Comment by vendeeglobe** [comment]
Yes I have read the wiki and the discussion. For this special case I prefer a configuration option and not have to maintain additional code.
