### ISSUE TITLE
Wiki (Updating, further ideas)

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#57]
I've added pages to the Wiki to make it more clear how to use PHP-diff.
https://github.com/JBlond/php-diff/wiki

@JBlond Please review the pages and comment below.

Let's keep this issue open for a while, so users also can make remarks and suggest additions in here.

**Comment by JBlond** [comment]
I like the pages. Well done.

It might be worth to mention the CSS files to modify the HTML output.

**Comment by DigiLive** [comment]
I'll add a styling page, explaining how to style html- or cli output.

**Comment by DigiLive** [comment]
Styling page is added to the wiki.
Feel free to correct any mistakes.

**Comment by JBlond** [comment]
We should add a link or a hint in the README.md to the wiki.

**Comment by JBlond** [comment]
The marking levels are not documented yet.

**Comment by DigiLive** [comment]
> 
> 
> The marking levels are not documented yet.

Just added to https://github.com/JBlond/php-diff/wiki/2.-Parameters-and-Options#options-1

**Comment by JBlond** [comment]
Further discussion at https://github.com/JBlond/php-diff/discussions/92
