### ISSUE TITLE
Side by side diff shows empty diff

### ISSUE THREAD

**Issue by vendeeglobe** [JBlond/php-diff#58]
Using php-diff version 2.2.0. In my use case this happens when I use pipes for the table syntax. Looks like a line break issue to me.

![inline_diff](https://user-images.githubusercontent.com/54716082/89385659-3b1dc500-d700-11ea-8291-43a3f5e2c39e.png)
![side-by-side_diff](https://user-images.githubusercontent.com/54716082/89385668-41ac3c80-d700-11ea-80fd-403f14ad8184.png)

[version_a.txt](https://github.com/JBlond/php-diff/files/5026894/version_a.txt)
[version_b.txt](https://github.com/JBlond/php-diff/files/5026897/version_b.txt)

**Comment by DigiLive** [comment]
Can you please confirm above commit resolves the issue.
The output is like previous versions and as expected?

**Comment by vendeeglobe** [comment]
Patch tested and it works.
![side-by-side_diff_patched](https://user-images.githubusercontent.com/54716082/89418178-0295df80-d730-11ea-9034-a7cdc4179b58.png)

**Comment by DigiLive** [comment]
Thank you for the feedback.
We'll release an update asap.

@JBlond I think a part of the code was removed due merging a pr. However, I'm not sure. Maybe we must consider a branching model to minimize these errors.

**Comment by JBlond** [comment]
@vendeeglobe The new release is there with the fix.
