### ISSUE TITLE
Unified Cli renderer options incompatible with Main renderer options.

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#60]
The UnifiedCli renderer has option `cliColor` whose only valid value is `simple`
`$this->options['cliColor'] == 'simple'`

The Main renderer has the following options:
```php
    /**
     * @var array   Associative array containing the default options available for this renderer and their default
     *              value.
     *              - tabSize           The amount of spaces to replace a tab character with.
     *              - format            The format of the input texts.
     *              - cliColor          Colorized output for cli.
     *              - deleteMarkers     Markers for removed text.
     *              - insertMarkers     Markers for inserted text.
     *              - equalityMarkers   Markers for unchanged and changed lines.
     *              - insertColors      Fore- and background color for inserted text. Only when cloColor = true.
     *              - deleteColors      Fore- and background color for removed text. Only when cloColor = true.
     */
    protected $mainOptions = [
        'tabSize'         => 4,
        'format'          => 'plain',
        'cliColor'        => false,
        'deleteMarkers'   => ['', ''],
        'insertMarkers'   => ['', ''],
        'equalityMarkers' => ['', ''],
        'insertColors'    => ['black', 'green'],
        'deleteColors'    => ['black', 'red'],
    ];
```
Option `cliColor` should be of type boolean and when `true` the output should be colorized using the colors defined at options `insertColors` and `deleteColors`.

btw... The comments in the code block above contains typos as well: `cloColor` instead of `cliColor`
See https://github.com/JBlond/php-diff/blob/e6812d018163a60261136621c4cb05499ab995c9/lib/jblond/Diff/Renderer/MainRendererAbstract.php#L39 and https://github.com/JBlond/php-diff/blob/e6812d018163a60261136621c4cb05499ab995c9/lib/jblond/Diff/Renderer/MainRendererAbstract.php#L40

**Comment by JBlond** [comment]
Feel very free to change that as you like. We can do a new version number that indicates that it is incompatible.

**Comment by JBlond** [comment]
See my suggestion https://github.com/JBlond/php-diff/pull/61

**Comment by JBlond** [comment]
I wonder if the constructor can be changed from 

```PHP
    public function __construct(array $options = [])
    {
        parent::__construct();
        $this->setOptions($this->subOptions);
        $this->setOptions($options);
    }
```

to

```PHP
    public function __construct(array $options = [])
    {
        parent::__construct($options);
    }
```

since the subOptions are empty in InlineCli

**Comment by DigiLive** [comment]
See my comment at https://github.com/JBlond/php-diff/pull/61#discussion_r500811768
I think it's the same subject?

subOptions is currently empty, but meant to declare default values for the subRenderer, other than the options of MainRenderer.
(Something like being futureproof)

**Comment by JBlond** [comment]
I still wonder then, why the constructor has the parameter, if setOptions should be used.

**Comment by DigiLive** [comment]
Stop wondering, your thoughts are right.
Just wanted to make clear why `$this->subOptions` exists and all options need to be merged.

The constructor of MainRendererAbstract also uses setOptions.

```php
    public function __construct(array $options = [])
    {
        parent::__construct();
        $this->setOptions($this->subOptions);
        $this->setOptions($options);
    }
```

could probably be shortened to:

```php
    public function __construct(array $options = [])
    {
        parent::__construct($this->subOptions);
        $this->setOptions($options);
        // Or switch $this->subOptions and $options.
    }
```

**Comment by JBlond** [comment]
It makes sense to set $options at last. Otherwise you can't override the default subOptions.

**Comment by JBlond** [comment]
Done. Merge #61
