### ISSUE TITLE
Update Diff 

### ISSUE THREAD

**Issue by JBlond** [JBlond/php-diff#75]
https://github.com/JBlond/php-diff/blob/master/lib/jblond/Diff.php#L53 has array<string, string> while it isn't correct.

**Comment by JBlond** [comment]
Should be changed to _array<string, string, int, bool>_

**Comment by DigiLive** [comment]
Out of interest...
On which syntax is this based?
For now `$defaultOptions` is an array with `string` as keys and `int | bool` as values.

**Comment by JBlond** [comment]
If you say it like this, it makes sense. Maybe just a brain fart idea. I was wondering how to fix https://insight.sensiolabs.com/projects/aa609edb-cdb1-45cf-ad51-afbdab48f6a1/analyses/124

**Comment by DigiLive** [comment]
Well... As I can't see their explanation, here's my 5 cents...

I'm guessing we both use PhpStorm as IDE.
When annotating the property, the quick documentation will show the default contents of it anyway:
![afbeelding](https://user-images.githubusercontent.com/7613487/99256916-727b3200-2816-11eb-88fd-9ebeb991f0d1.png)

To me, this is fine enough.
Hopefully, annotations become standardized and the IDE will support that annotation syntax in the nearby future.
