### ISSUE TITLE
Invalid version constraint

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#76]
https://github.com/JBlond/php-diff/blob/6fecd037f3dc7181b2a86d549bc2252ee9c44f79/composer.json#L34

Makes packagist giving an error:

Importing branch automatic-changelog (dev-automatic-changelog)
Skipped branch automatic-changelog, Invalid package information:
require-dev.phpunit/phpunit : invalid version constraint (Could not parse version constraint ^9.*: Invalid version string "^9.*")

**Comment by JBlond** [comment]
I've changed that.
