### ISSUE TITLE
Lines with differences from start- to endcharacter not properly marked

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#83]
If a line is different at the other version from the first to the last character, the line isn't marked when `inlineMarking` is set to `CHANGE_LEVEL_LINE`.

**Comment by DigiLive** [comment]
I think it's the following line to blame, but it's imported when the lib was forked:
https://github.com/JBlond/php-diff/blob/0bd0bd2708b99dddc7515c19a309ba51868e449c/lib/jblond/Diff/Renderer/MainRenderer.php#L313

I think...
...it can be safely removed.
`$start` and `$end` will both be `0` when the first difference is at the start of the string and the last difference at the end.
Imho, the complete string should be marked as being different.

...it was meant for skipping code when there aren't any differences found by method `getOuterChange`.
However, method `markOuterChange` is only called by `renderSequences > markInlineChanges` if the opCode tag is `replace` anyway. Which means something must be different.

**Comment by JBlond** [comment]
> I think...
> ...it can be safely removed.

Easy to find out. remove the lines, run the unit tests, run a visual test and create a PR :D

**Comment by DigiLive** [comment]
Haha... I will.
Not very sure this time because it's always been there and the sample texts don't cover all cases.

**Comment by vendeeglobe** [comment]
We collect and cover all new cases as soon as we discover them.
