### ISSUE TITLE
add method to get diff statistics

### ISSUE THREAD

**Issue by vendeeglobe** [JBlond/php-diff#97]
I'd like to have a option to add diff statistics for the diff meta header.

example:
Added - 5 lines, deleted - 10 lines, updated - 2 lines, unmodified - 250 lines

see: https://github.com/jfcherng/php-diff/commit/4b170cd79403a8723024eea3dfb62651735d0547

**Comment by JBlond** [comment]
@vendeeglobe There is now https://github.com/JBlond/php-diff/pull/100 
However I haven't tested it enough. The number of not modified lines seems to be odd so far.

**Comment by vendeeglobe** [comment]
It seems it counts the chunks and not the lines.

**Comment by JBlond** [comment]
this has bens solves with #108
